# Multi-Agent Deliberation settings
mode: "deliberate"  # Options: "deliberate" (plan→approve→execute) | "direct" (execute immediately, no planning)
max_turns: 5
transcript_path: "reports/conversation.jsonl"
proposer_id: "claude-code"   # Agent A
critic_id:   "codex"         # Agent B

# Consensus criteria (checked by the critic or the orchestrator)
consensus:
  require_critic_approved: true
  require_plan_valid: true

# Success guardrails (advisory to agents; also enforced by your reviewer)
guardrails:
  require_download_root: "staging/"
  require_ingest: true
  min_unique_channels: 3
  require_tags: true
